### ISSUE TITLE
Cannot connect to CubeSql in local network

### ISSUE THREAD

**Issue by ninja-pinky** [cubesql/cubeSQLAdmin#5]
How I can connect to CubeSql in the same network from another machine?

**Comment by marcobambini** [comment]
Not sure to understand, just enter its IP address to connect.

**Comment by ninja-pinky** [comment]
I have installed CubeSql in both machines(Windows, Mac) I want to access to CubeSql Server(Located in MAC  ) from Windows 

Machine or to CubeSql Server(Located in Windows) from Mac via the IP address (Local Network).

After disabling the Firewall on windows i can now access the CubeSql Server (Located in Windows ) from MAC Machine. But I can't 

access to the CubeSql Server(Located in MAC ) from Windows Machine, although I disabled the firewall in MAC.

**Comment by oleman108** [comment]
It is definitely possible to access a cubeSQL Server on macOS, I have it running here. If you already disabled the firewall you have to check all other details again: no other restrictive software running on that mac, like Little Snitch, etc? IPs and Port addresses are correct? Can you ping that mac over the LAN?

Good luck, Oliver

_____________________

Rabten Stiftung
Oliver Osswald
Route Praz-Valey 4
CH 1801 Le Mont-Pèlerin
+41-76-210-5000
***@***.***
https://rabten.com <https://rabten.com/>
_____________________

**Comment by RothSoft-jotter** [comment]
> I want to access to CubeSql Server(Located in MAC ) from Windows

Please note:
**CubeSQLPlugin** has integrated SSL Libraries on macOS, but not on Windows.


You'll find the answer looking at the Code of CubeSQLAdmin:

In `App.SSLStartupCheck` the CubeSQLAdmin.app is looking for a folder named `SSL` next to the executable file, or a folder named `cubeSQLAdmin SSL`:

```
// first check for a SSL folder next to executable
Dim f As FolderItem = GetFolderItem("")
if (f <> nil) then f = f.Child("SSL")
if (f <> nil) and (f.Exists) then return f

// then lookup in ApplicationData folder
f = SpecialFolder.ApplicationData
if (f <> nil) then f = f.Child("cubeSQLAdmin SSL")
if (f <> nil) and (f.Exists) then return f
```

In there, it expects that you provide your own OpenSSL Library (.dll):

```
Dim SSLLib As String
Dim CryptoLib As String
...
#elseif TargetWindows
SSLLib = "libssl32.dll"
CryptoLib = "libeay32.dll"
```

So... if you're running the Windows 32-Bit app of CubeSQLAdmin: Create a Folder named "SSL" next to the executable, and put the .dll's in there.
If you're going to use the Windows 64-Bit app of CubeSQLAdmin, you'll either have to modify and compile the project yourself (and adjust the code to find the correct .dll's - they're named differently in their 64Bit editions by default), or rename the 64Bit .dll's so that CubeSQLAdmin finds them.

The same applies to applications you're going to build and run on TargetWindows.
You'll need to provide the OpenSSL Libraries (.dll's) yourself.

It boils down to this two lines of code, where the OpenSSL Libraries need to be set for TargetWindows:

```
CubeSQLPlugin.SSLLibrary = SSLLibPath
CubeSQLPlugin.CryptoLibrary = CryptoLibPath
```

**Comment by ninja-pinky** [comment]
It works now after restarting the Mac computer and disabling the firewall.
Thanks
