### ISSUE TITLE
cubeSQLAdmin with SSL encryption on Windows

### ISSUE THREAD

**Issue by joseluisq** [cubesql/cubeSQLAdmin#6]
Hi
I have already a cubeSQL instance for testing accepting only SSL clients. I have configured using a testing cert.
You can see it running like: `CubeSQL Server version 5.8.0 64bit mode, Build Date Sep 26 2020 (SQLite Engine 3.33.0), TSL Library is LibreSSL 3.1.4`

But when I try to connect from a Windows 10 client then I got this error.

![image](https://user-images.githubusercontent.com/1700322/146570270-5d539772-44e9-4f79-bffd-42517cc455a8.png)

But If I try the same admin from a Mac computer it works.

Maybe am I forgetting some dependency on the Windows system?

On the Mac computer I have

```
openssl version
LibreSSL 2.8.3
```

Thanks

**Comment by jo-tools** [comment]
> when I try to connect from a Windows 10 client then I got this error: `SSL Library not found`
> If I try the same admin from a Mac computer it works.
> Maybe am I forgetting some dependency on the Windows system?

Please note:
**CubeSQLPlugin** has integrated SSL Libraries on macOS, but not on Windows.


You'll find the answer looking at the Code of CubeSQLAdmin:

In `App.SSLStartupCheck` the CubeSQLAdmin.app is looking for a folder named `SSL` next to the executable file, or a folder named `cubeSQLAdmin SSL`:

```
// first check for a SSL folder next to executable
Dim f As FolderItem = GetFolderItem("")
if (f <> nil) then f = f.Child("SSL")
if (f <> nil) and (f.Exists) then return f

// then lookup in ApplicationData folder
f = SpecialFolder.ApplicationData
if (f <> nil) then f = f.Child("cubeSQLAdmin SSL")
if (f <> nil) and (f.Exists) then return f
```

In there, it expects that you provide your own OpenSSL Library (.dll):

```
Dim SSLLib As String
Dim CryptoLib As String
...
#elseif TargetWindows
SSLLib = "libssl32.dll"
CryptoLib = "libeay32.dll"
```

So... if you're running the Windows 32-Bit app of CubeSQLAdmin: Create a Folder named "SSL" next to the executable, and put the .dll's in there.
If you're going to use the Windows 64-Bit app of CubeSQLAdmin, you'll either have to modify and compile the project yourself (and adjust the code to find the correct .dll's - they're named differently in their 64Bit editions by default), or rename the 64Bit .dll's so that CubeSQLAdmin finds them.

The same applies to applications you're going to build and run on TargetWindows.
You'll need to provide the OpenSSL Libraries (.dll's) yourself.

It boils down to this two lines of code, where the OpenSSL Libraries need to be set for TargetWindows:

```
CubeSQLPlugin.SSLLibrary = SSLLibPath
CubeSQLPlugin.CryptoLibrary = CryptoLibPath
```

**Comment by joseluisq** [comment]
> **CubeSQLPlugin** has integrated SSL Libraries on macOS, but not on Windows.

I was not aware about this. I thought that it was similar to the server like the added built-in support for OpenSSL (via LibreSSL) on 5.8.0.

--

Yeah we rebuilt the project providing openssl along with latest Xojo and it works as expected.
Thanks for the hint.
