### ISSUE TITLE
cubeSQLAdmin crashes on Windows when wrong SSL certificates used but not possible to handle the runtime exception

### ISSUE THREAD

**Issue by joseluisq** [cubesql/cubeSQLAdmin#8]
When I did try to play with `cubeSQLAdmin` (latest Xojo R3.1) and SSL connection on Windows 10 (x64) but If I use wrong certificates **_on purpose_** it simply crashes but unfortunately a Xojo try/catch block can not handle it because the program just terminates either in Xojo debug or prod mode.

The OpenSSL runtime error is shown bellow.

![image](https://user-images.githubusercontent.com/1700322/150174347-a12f7110-0632-4671-bb55-5ae9f67404cc.png)

**How to reproduce the crash**

This was tested on Windows 10

1. Configure a Linux cubesql server using strict SSL with peer verification (cert + root) - Of course I use two valid certificates, not self-signed ones.
2. On cubesqlAdmin, create an "SSL" dir on the current project and include **INVALID** `admin.pem` and `root.pem` certificate files.
3. Then after press on cubesqlAdmin's `connect` button you will see that a `no OPENSSL_Applink runtime error` and the program exits.

In the other hand, if one tries to use **VALID** certificates of course it works.

--

But as I told I have tried (but without success) to handle this using a trivial try/catch block but it can't catch the OpenSSL exception.
So I don't know if this is related to how **cubeSQL Xojo Plugin** handles OpenSSL runtime errors or if I missed something on the code.

But whatever guidance to address the problem for this use case will be very appreciated.

**Comment by joseluisq** [comment]
**Note:** In the screenshot I use a valid hostname but I have "hidden" the domain and added some highlights for better understanding.

**Comment by jo-tools** [comment]
This can be reproduced with cubeSQLAdmin.
1. Launch CubeSQL Server (default; no SSL settings)
2. Launch cubeSQLAdmin, select "Encryption: SSL", click "Connect"

**macOS**
The expected result: an error message.
<img width="712" alt="cubeSQLAdmin_SSL_macOS" src="https://user-images.githubusercontent.com/11751753/216443227-7d9c65c7-97eb-47a3-8680-39ebaa339cf3.png">

**Windows**
A fatal result which can't be catched and leads to a crash of the built application.
![cubeSQLAdmin_SSL_Windows](https://user-images.githubusercontent.com/11751753/216443519-4365d3dd-8bac-445d-80f3-14a3d03bc86c.png)


CubeSQL Server Log:
![cubeSQL_Server](https://user-images.githubusercontent.com/11751753/216443639-261b913f-4b4e-4f05-9625-dad75c2640e2.png)


@marcobambini This issue needs to be fixed in `CubeSQLPlugin`.

**Comment by marcobambini** [comment]
Fixed with the latest CubeSQLPlugin available from https://github.com/marcobambini/cubesqlplugin
